# Generated by Django 5.0.6 on 2024-07-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_slug_alter_subject_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='course_default.jpg', upload_to='course_images'),
        ),
    ]
